In [1]:
import pandas as pd
import numpy as np

In [2]:
mat = np.random.random((10,5))

In [3]:
mat

array([[0.54495343, 0.0875598 , 0.53979991, 0.41580696, 0.69714375],
       [0.76077153, 0.69424826, 0.45715077, 0.34324998, 0.12683783],
       [0.75573485, 0.52551474, 0.44718341, 0.61655524, 0.11244548],
       [0.83734257, 0.84176344, 0.55387634, 0.40796907, 0.4614907 ],
       [0.26852818, 0.23306688, 0.55576671, 0.73240803, 0.97328195],
       [0.01269535, 0.64414637, 0.56166437, 0.61615014, 0.71819047],
       [0.28606991, 0.63423257, 0.91347586, 0.1146067 , 0.97639269],
       [0.20119126, 0.98037032, 0.97025616, 0.44764998, 0.85920067],
       [0.85934004, 0.70395991, 0.94804208, 0.83824589, 0.48451764],
       [0.68817262, 0.77988246, 0.85005287, 0.8645605 , 0.65390222]])

In [4]:
data = pd.DataFrame(mat,columns=['one','two','three','four','five'])

In [5]:
data

        one       two     three      four      five
0  0.544953  0.087560  0.539800  0.415807  0.697144
1  0.760772  0.694248  0.457151  0.343250  0.126838
2  0.755735  0.525515  0.447183  0.616555  0.112445
3  0.837343  0.841763  0.553876  0.407969  0.461491
4  0.268528  0.233067  0.555767  0.732408  0.973282
5  0.012695  0.644146  0.561664  0.616150  0.718190
6  0.286070  0.634233  0.913476  0.114607  0.976393
7  0.201191  0.980370  0.970256  0.447650  0.859201
8  0.859340  0.703960  0.948042  0.838246  0.484518
9  0.688173  0.779882  0.850053  0.864561  0.653902

In [6]:
data.values

array([[0.54495343, 0.0875598 , 0.53979991, 0.41580696, 0.69714375],
       [0.76077153, 0.69424826, 0.45715077, 0.34324998, 0.12683783],
       [0.75573485, 0.52551474, 0.44718341, 0.61655524, 0.11244548],
       [0.83734257, 0.84176344, 0.55387634, 0.40796907, 0.4614907 ],
       [0.26852818, 0.23306688, 0.55576671, 0.73240803, 0.97328195],
       [0.01269535, 0.64414637, 0.56166437, 0.61615014, 0.71819047],
       [0.28606991, 0.63423257, 0.91347586, 0.1146067 , 0.97639269],
       [0.20119126, 0.98037032, 0.97025616, 0.44764998, 0.85920067],
       [0.85934004, 0.70395991, 0.94804208, 0.83824589, 0.48451764],
       [0.68817262, 0.77988246, 0.85005287, 0.8645605 , 0.65390222]])

In [3]:
x = [1,2,3,4,5,6]

In [4]:
pd.Series(x)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [28]:
data

        one       two     three      four      five
0  0.358485  0.465902  0.965839  0.167970  0.247310
1  0.433846  0.046145  0.388144  0.703129  0.226919
2  0.572146  0.766710  0.308326  0.794596  0.337496
3  0.038358  0.131828  0.014103  0.546178  0.158041
4  0.598886  0.184197  0.686995  0.014938  0.224375
5  0.342660  0.918536  0.729465  0.874479  0.008598
6  0.082725  0.973164  0.287235  0.304019  0.047920
7  0.930006  0.473718  0.913353  0.841217  0.310784
8  0.819818  0.184571  0.353395  0.839852  0.070395
9  0.331662  0.183612  0.560609  0.278938  0.414621

In [33]:
data.tail()

        one       two     three      four      five
5  0.342660  0.918536  0.729465  0.874479  0.008598
6  0.082725  0.973164  0.287235  0.304019  0.047920
7  0.930006  0.473718  0.913353  0.841217  0.310784
8  0.819818  0.184571  0.353395  0.839852  0.070395
9  0.331662  0.183612  0.560609  0.278938  0.414621

In [ ]:
data.shape
data.columns
data.index
data.info()
data.describe()
data.head()
data.tail()

In [20]:
data = pd.read_csv('Mall_Customers.csv',encoding='utf-8')

In [21]:
data.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [76]:
data.iloc[:,:]

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6

In [81]:
data.loc[3:7,'CustomerID':'Age']

   CustomerID   Genre  Age
3           4  Female   23
4           5  Female   31
5           6  Female   22
6           7  Female   35
7           8  Female   23

In [82]:
!pip list

Package                            Version
---------------------------------- -------------------
absl-py                            0.11.0
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
argh                               0.26.2
asn1crypto                         1.3.0
astroid                            2.4.2
astropy                            4.0.1.post1
astunparse                         1.6.3
atomicwrites                       1.4.0
attrs                              19.3.0
autopep8                           1.5.3
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.1.7
beautifulsoup4                     4.9.1
bitarray                           1.4.0
bkcharts                           0.2
bleach                             3.1.5
bokeh                              2.1.1
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
cachetools                         4.1.1
certifi                            2020.6.20
cffi                               1.14.0
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.5.0
clyent                             1.2.2
colorama                           0.4.3
comtypes                           1.1.7
conda                              4.8.3
conda-build                        3.18.11
conda-package-handling             1.7.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cryptography                       2.9.2
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.10.1
dask                               2.20.0
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2.20.0
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.8.3
Flask                              1.1.2
fsspec                             0.7.4
future                             0.18.2
gast                               0.3.3
gevent                             20.6.2
glob2                              0.7
gmpy2                              2.0.8
google-auth                        1.23.0
google-auth-oauthlib               0.4.2
google-pasta                       0.2.0
greenlet                           0.4.16
grpcio                             1.33.2
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
imbalanced-learn                   0.7.0
imblearn                           0.0
importlib-metadata                 1.7.0
intervaltree                       3.0.2
ipykernel                          5.3.2
ipython                            7.16.1
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             2.11.2
joblib                             0.16.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.6
jupyter-console                    6.1.0
jupyter-core                       4.6.3
jupyterlab                         2.1.5
jupyterlab-server                  1.2.0
Keras                              2.4.3
Keras-Preprocessing                1.1.2
keyring                            21.2.1
kiwisolver                         1.2.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.33.0+1.g022ab0f
locket                             0.2.0
lxml                               4.5.2
Markdown                           3.3.3
MarkupSafe                         1.1.1
matplotlib                         3.2.2
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.1.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.4.0
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbconvert                          5.6.1
nbformat                           5.0.7
networkx                           2.4
nltk                               3.5
nose                               1.3.7
notebook                           6.0.3
numba                              0.50.1
numexpr                            2.7.1
numpy                              1.18.5
numpydoc                           1.1.0
oauthlib                           3.1.0
olefile                            0.46
openpyxl                           3.0.4
opt-einsum                         3.3.0
packaging                          20.4
pandas                             1.0.5
pandocfilters                      1.4.2
paramiko                           2.7.1
parso                              0.7.0
partd                              1.1.0
path                               13.1.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             7.2.0
pip                                20.1.1
pkginfo                            1.5.0.1
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.8.0
prompt-toolkit                     3.0.5
protobuf                           3.13.0
psutil                             5.7.0
py                                 1.9.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.5
pydocstyle                         5.0.2
pyflakes                           2.2.0
Pygments                           2.6.1
pylint                             2.5.3
pymongo                            3.11.0
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyreadline                         2.1
pyrsistent                         0.16.0
PySocks                            1.7.1
pytest                             5.4.3
python-dateutil                    2.8.1
python-jsonrpc-server              0.3.4
python-language-server             0.34.1
pytz                               2020.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.3.1
pyzmq                              19.0.1
QDarkStyle                         2.8.1
QtAwesome                          0.7.2
qtconsole                          4.7.5
QtPy                               1.9.0
regex                              2020.6.8
requests                           2.24.0
requests-oauthlib                  1.3.0
rope                               0.17.0
rsa                                4.6
Rtree                              0.9.4
ruamel-yaml                        0.15.87
scikit-image                       0.16.2
scikit-learn                       0.23.1

scipy                              1.5.0
seaborn                            0.10.1
selenium                           3.141.0
Send2Trash                         1.5.0
setuptools                         49.2.0.post20200714
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                4.19.13
six                                1.15.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.1.2
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.3
spyder                             4.1.4
spyder-kernels                     1.9.2
SQLAlchemy                         1.3.18
statsmodels                        0.11.1
sympy                              1.6.1
tables                             3.6.1
tblib                              1.6.0
tensorboard                        2.3.0
tensorboard-plugin-wit             1.7.0
tensorflow-gpu                     2.3.1
tensorflow-gpu-estimator           2.3.0
termcolor                          1.1.0
terminado                          0.8.3
testpath                           0.4.4
threadpoolctl                      2.1.0
toml                               0.10.1
toolz                              0.10.0
tornado                            6.0.4
tqdm                               4.47.0
traitlets                          4.3.3
typing-extensions                  3.7.4.2
ujson                              1.35
unicodecsv                         0.14.1
urllib3                            1.25.9
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.34.2
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.2
xlrd                               1.2.0
XlsxWriter                         1.2.9
xlwings                            0.19.5
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.1.0
zope.event                         4.4
zope.interface                     4.7.1